/* Traductions : clé -> [FR, EN, AR] */
const T={
'top.phone':['+212 5 22 00 00 00','+212 5 22 00 00 00','+212 5 22 00 00 00'],
'top.mail':['contact@darna-immobilier.ma','contact@darna-immobilier.ma','contact@darna-immobilier.ma'],
'top.hours':['Lun–Sam : 9h – 19h','Mon–Sat: 9am – 7pm','الإثنين–السبت: 9ص – 7م'],
'nav.home':['Accueil','Home','الرئيسية'],'nav.biens':['Nos Biens','Properties','عقاراتنا'],'nav.contact':['Contact & Simulateur','Contact & Simulator','اتصل بنا والمحاكي'],
'hero.kicker':['Agence immobilière au Maroc','Real estate agency in Morocco','وكالة عقارية بالمغرب'],
'hero.title':['Trouvez la maison qui vous ressemble','Find the home that feels like yours','اعثر على المنزل الذي يشبهك'],
'hero.sub':['Appartements, villas, riads et locaux professionnels à Casablanca, Rabat, Marrakech, Tanger et Fès.','Apartments, villas, riads and commercial spaces in Casablanca, Rabat, Marrakech, Tangier and Fez.','شقق وفيلات ورياضات ومحلات مهنية في الدار البيضاء والرباط ومراكش وطنجة وفاس.'],
'hero.cta1':['Voir les biens','Browse properties','تصفح العقارات'],'hero.cta2':['Simuler mon crédit','Simulate my loan','محاكاة قرضي'],
'stat1':['Biens vendus','Properties sold','عقار مباع'],'stat2':['Clients satisfaits','Happy clients','عميل راض'],'stat3':["Ans d'expérience",'Years of experience','سنة من الخبرة'],'stat4':['Conseillers','Advisors','مستشارا'],
'sec.serv.k':['Nos services','Our services','خدماتنا'],'sec.serv.t':['Un accompagnement complet','End-to-end support','مواكبة شاملة'],'sec.serv.p':["De la recherche à la remise des clés, nous restons à vos côtés.",'From search to key handover, we stay by your side.','من البحث إلى تسليم المفاتيح، نحن بجانبكم.'],
'serv1.t':['Achat','Buying','الشراء'],'serv1.p':['Sélection de biens vérifiés, visites et négociation.','Verified listings, viewings and negotiation.','عقارات موثقة وزيارات ومفاوضات.'],
'serv2.t':['Location','Renting','الكراء'],'serv2.p':['Contrats sécurisés et gestion locative.','Secure contracts and property management.','عقود آمنة وتدبير الكراء.'],
'serv3.t':['Estimation','Valuation','التقييم'],'serv3.p':['Estimation précise selon le marché local.','Accurate valuation based on the local market.','تقييم دقيق حسب السوق المحلي.'],
'serv4.t':['Financement','Financing','التمويل'],'serv4.p':['Simulation et montage de votre crédit immobilier.','Loan simulation and mortgage set-up.','محاكاة وإعداد قرضكم العقاري.'],
'sec.feat.k':['Sélection','Selection','مختارات'],'sec.feat.t':['Biens à la une','Featured properties','عقارات مميزة'],'sec.feat.p':['Nos coups de cœur du moment.','Our current favourites.','اختياراتنا المفضلة حاليا.'],'feat.all':['Tous les biens','All properties','كل العقارات'],
'sec.why.t':['Pourquoi Darna ?','Why Darna?','لماذا دارنا؟'],'sec.why.p':["Transparence, rigueur et connaissance du terrain.",'Transparency, rigour and local knowledge.','شفافية ودقة ومعرفة بالميدان.'],
'why1.t':['Biens vérifiés','Verified listings','عقارات موثقة'],'why1.p':['Titres fonciers contrôlés.','Land titles checked.','رسوم عقارية مدققة.'],
'why2.t':['Prix justes','Fair prices','أسعار عادلة'],'why2.p':['Estimations basées sur le marché.','Market-based valuations.','تقييمات مبنية على السوق.'],
'why3.t':['5 villes','5 cities','5 مدن'],'why3.p':['Présence locale partout.','Local presence everywhere.','حضور محلي في كل مكان.'],
'why4.t':['Partenaires bancaires','Banking partners','شركاء بنكيون'],'why4.p':['Des offres de crédit négociées.','Negotiated loan offers.','عروض قروض مفاوض عليها.'],
'sec.testi.k':['Avis','Reviews','آراء'],'sec.testi.t':['Ils nous ont fait confiance','They trusted us','وثقوا بنا'],
't1':["Un appartement trouvé en deux semaines, avec un suivi impeccable.",'We found an apartment in two weeks, with flawless follow-up.','وجدنا شقة في أسبوعين مع متابعة ممتازة.'],'t1w':['Salma B.','Salma B.','سلمى ب.'],'t1r':['Acheteuse, Casablanca','Buyer, Casablanca','مشترية، الدار البيضاء'],
't2':["Vente de notre villa au bon prix, démarches simples.",'Our villa sold at the right price, simple paperwork.','بعنا الفيلا بسعر مناسب وإجراءات بسيطة.'],'t2w':['Karim E.','Karim E.','كريم إ.'],'t2r':['Vendeur, Rabat','Seller, Rabat','بائع، الرباط'],
't3':["Équipe réactive pour notre riad à Marrakech.",'A responsive team for our riad in Marrakech.','فريق متجاوب بخصوص رياضنا بمراكش.'],'t3w':['Yasmine L.','Yasmine L.','ياسمين ل.'],'t3r':['Investisseuse, Marrakech','Investor, Marrakech','مستثمرة، مراكش'],
'sec.cta.t':['Un projet immobilier ?','Planning a property project?','هل لديك مشروع عقاري؟'],'sec.cta.p':['Parlons-en : réponse sous 24h.','Let’s talk: we reply within 24h.','لنتحدث: نجيب خلال 24 ساعة.'],'sec.cta.b':['Nous contacter','Contact us','تواصل معنا'],
'biens.title':['Nos Biens','Our Properties','عقاراتنا'],'biens.sub':['12 annonces sélectionnées dans 5 villes.','12 hand-picked listings across 5 cities.','12 إعلانا مختارا في 5 مدن.'],
'f.type':['Type de bien','Property type','نوع العقار'],'f.all':['Tous','All','الكل'],'f.city':['Ville','City','المدينة'],'f.any':['Indifférent','Any','أي'],'f.budget':['Budget max (MAD)','Max budget (MAD)','الميزانية القصوى (درهم)'],'f.rooms':['Chambres min.','Min. bedrooms','غرف على الأقل'],'f.reset':['Réinitialiser','Reset','إعادة تعيين'],
't.apartment':['Appartement','Apartment','شقة'],'t.villa':['Villa','Villa','فيلا'],'t.riad':['Riad','Riad','رياض'],'t.office':['Bureau','Office','مكتب'],'t.shop':['Local commercial','Shop','محل تجاري'],
'c.casablanca':['Casablanca','Casablanca','الدار البيضاء'],'c.rabat':['Rabat','Rabat','الرباط'],'c.marrakech':['Marrakech','Marrakech','مراكش'],'c.tanger':['Tanger','Tangier','طنجة'],'c.fes':['Fès','Fez','فاس'],
'd.apartment':['Appartement lumineux, finitions soignées, résidence sécurisée.','Bright apartment with quality finishes in a secure residence.','شقة مشرقة بتشطيبات راقية في إقامة مؤمنة.'],
'd.villa':['Villa spacieuse avec jardin, idéale pour une famille.','Spacious villa with garden, ideal for families.','فيلا واسعة بحديقة، مثالية للعائلات.'],
'd.riad':['Riad authentique, patio et zellige traditionnel.','Authentic riad with patio and traditional zellige.','رياض أصيل بصحن وزليج تقليدي.'],
'd.office':['Plateau de bureaux moderne, bien desservi.','Modern, well-connected office floor.','مكتب عصري سهل الولوج.'],
'd.shop':['Local en pied d’immeuble, forte visibilité et passage.','Ground-floor unit with high visibility and foot traffic.','محل بالطابق الأرضي بواجهة وحركة قوية.'],
'x.pool':['Piscine','Pool','مسبح'],'x.garden':['Jardin','Garden','حديقة'],'x.parking':['Parking','Parking','موقف سيارات'],'x.terrace':['Terrasse','Terrace','شرفة'],'x.elevator':['Ascenseur','Elevator','مصعد'],'x.sea':['Vue mer','Sea view','إطلالة بحرية'],'x.sec':['Sécurité 24/7','24/7 security','حراسة 24/7'],'x.patio':['Patio','Patio','صحن'],'x.fiber':['Fibre','Fiber','ألياف'],'x.ac':['Climatisation','A/C','تكييف'],'x.new':['Neuf','New build','جديد'],
'tag.new':['Nouveau','New','جديد'],'tag.excl':['Exclusivité','Exclusive','حصري'],
'p.rooms':['ch.','bd','غرف'],'p.baths':['sdb','ba','حمام'],'p.more':['Détails','Details','التفاصيل'],'cur':['MAD','MAD','درهم'],
'res':['{n} bien(s) trouvé(s)','{n} propert(ies) found','تم العثور على {n} عقار'],'none':['Aucun bien ne correspond. Élargissez vos critères.','No property matches. Try broader filters.','لا يوجد عقار مطابق. وسّع معايير البحث.'],
'foot.about':['Darna Immobilier vous accompagne dans tous vos projets au Maroc.','Darna Immobilier supports all your property projects in Morocco.','دارنا العقارية ترافقكم في جميع مشاريعكم بالمغرب.'],
'foot.nav':['Navigation','Navigation','التصفح'],'foot.contact':['Contact','Contact','تواصل'],'foot.news':['Adresse','Address','العنوان'],
'ct.addr':['Bd Zerktouni, Casablanca, Maroc','Bd Zerktouni, Casablanca, Morocco','شارع الزرقطوني، الدار البيضاء، المغرب'],
'contact.title':['Contact & Simulateur','Contact & Simulator','اتصل بنا والمحاكي'],'contact.sub':['Une question ? Un projet ? Écrivez-nous.','A question? A project? Write to us.','سؤال؟ مشروع؟ راسلونا.'],
'ct.info.t':['Nos coordonnées','Our details','معلومات الاتصال'],'ct.info.p':['Nous répondons sous 24h.','We reply within 24h.','نجيب خلال 24 ساعة.'],'ct.form.t':['Écrivez-nous','Send a message','راسلنا'],'ct.form.p':['Remplissez le formulaire ci-dessous.','Fill in the form below.','املأ النموذج أدناه.'],
'fm.name':['Nom complet','Full name','الاسم الكامل'],'fm.phone':['Téléphone','Phone','الهاتف'],'fm.mail':['E-mail','Email','البريد الإلكتروني'],'fm.subject':['Sujet','Subject','الموضوع'],
'fm.s1':['Acheter un bien','Buy a property','شراء عقار'],'fm.s2':['Louer un bien','Rent a property','كراء عقار'],'fm.s3':['Vendre mon bien','Sell my property','بيع عقاري'],'fm.s4':['Financement','Financing','التمويل'],'fm.s5':['Autre','Other','آخر'],
'fm.msg':['Votre message','Your message','رسالتك'],'fm.send':['Envoyer','Send','إرسال'],'fm.ok':['Merci ! Votre message a bien été envoyé.','Thank you! Your message has been sent.','شكرا! تم إرسال رسالتك.'],
'sim.t':['Simulateur de crédit immobilier','Mortgage simulator','محاكي القرض العقاري'],'sim.p':['Estimez votre mensualité en quelques secondes.','Estimate your monthly payment in seconds.','قدّر قسطك الشهري في ثوان.'],
'sim.price':['Prix du bien','Property price','ثمن العقار'],'sim.down':['Apport','Down payment','الدفعة الأولى'],'sim.rate':['Taux annuel','Annual rate','نسبة الفائدة السنوية'],'sim.years':['Durée','Duration','المدة'],
'sim.monthly':['Mensualité estimée','Estimated monthly payment','القسط الشهري المقدر'],'sim.ratio':['Apport','Down','الدفعة'],'sim.amount':['Montant emprunté','Amount borrowed','المبلغ المقترض'],'sim.interests':['Total des intérêts','Total interest','مجموع الفوائد'],'sim.total':['Coût total du crédit','Total loan cost','التكلفة الإجمالية'],'yrs':['ans','yrs','سنة']
};
const LANGS=['fr','en','ar'];
const I18N={fr:{},en:{},ar:{}};
Object.keys(T).forEach(k=>LANGS.forEach((l,i)=>I18N[l][k]=T[k][i]));

/* Catalogue : 12 biens (prix en MAD) */
const PROPS=[
{id:1,type:'apartment',city:'casablanca',district:'Maârif',price:1850000,rooms:3,baths:2,area:112,x:['elevator','parking','sec'],tag:'new',feat:1},
{id:2,type:'villa',city:'marrakech',district:'Palmeraie',price:6900000,rooms:5,baths:4,area:420,x:['pool','garden','sec'],tag:'excl',feat:1},
{id:3,type:'riad',city:'marrakech',district:'Médina',price:4200000,rooms:5,baths:5,area:260,x:['patio','terrace'],feat:1},
{id:4,type:'apartment',city:'rabat',district:'Agdal',price:2350000,rooms:3,baths:2,area:128,x:['elevator','parking','fiber'],tag:'new',feat:1},
{id:5,type:'office',city:'casablanca',district:'Bd Zerktouni',price:3100000,rooms:4,baths:2,area:180,x:['ac','parking','fiber']},
{id:6,type:'shop',city:'tanger',district:'Centre-ville',price:1450000,rooms:1,baths:1,area:64,x:['fiber'],feat:1},
{id:7,type:'villa',city:'casablanca',district:'Anfa',price:9500000,rooms:5,baths:5,area:550,x:['pool','garden','sec'],tag:'excl',feat:1},
{id:8,type:'apartment',city:'tanger',district:'Malabata',price:1250000,rooms:2,baths:1,area:85,x:['sea','terrace']},
{id:9,type:'riad',city:'fes',district:'Fès el-Bali',price:2100000,rooms:4,baths:3,area:190,x:['patio','terrace']},
{id:10,type:'villa',city:'rabat',district:'Souissi',price:7800000,rooms:5,baths:4,area:480,x:['garden','pool','parking']},
{id:11,type:'apartment',city:'marrakech',district:'Guéliz',price:1680000,rooms:2,baths:2,area:94,x:['elevator','ac','new'],tag:'new'},
{id:12,type:'shop',city:'casablanca',district:'Gauthier',price:2750000,rooms:1,baths:1,area:90,x:['ac','fiber']}
];
